require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CiaosController do

  # This should return the minimal set of attributes required to create a valid
  # Ciao. As you add validations to Ciao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CiaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ciaos as @ciaos" do
      ciao = Ciao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ciaos).should eq([ciao])
    end
  end

  describe "GET show" do
    it "assigns the requested ciao as @ciao" do
      ciao = Ciao.create! valid_attributes
      get :show, {:id => ciao.to_param}, valid_session
      assigns(:ciao).should eq(ciao)
    end
  end

  describe "GET new" do
    it "assigns a new ciao as @ciao" do
      get :new, {}, valid_session
      assigns(:ciao).should be_a_new(Ciao)
    end
  end

  describe "GET edit" do
    it "assigns the requested ciao as @ciao" do
      ciao = Ciao.create! valid_attributes
      get :edit, {:id => ciao.to_param}, valid_session
      assigns(:ciao).should eq(ciao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ciao" do
        expect {
          post :create, {:ciao => valid_attributes}, valid_session
        }.to change(Ciao, :count).by(1)
      end

      it "assigns a newly created ciao as @ciao" do
        post :create, {:ciao => valid_attributes}, valid_session
        assigns(:ciao).should be_a(Ciao)
        assigns(:ciao).should be_persisted
      end

      it "redirects to the created ciao" do
        post :create, {:ciao => valid_attributes}, valid_session
        response.should redirect_to(Ciao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ciao as @ciao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ciao.any_instance.stub(:save).and_return(false)
        post :create, {:ciao => {}}, valid_session
        assigns(:ciao).should be_a_new(Ciao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ciao.any_instance.stub(:save).and_return(false)
        post :create, {:ciao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ciao" do
        ciao = Ciao.create! valid_attributes
        # Assuming there are no other ciaos in the database, this
        # specifies that the Ciao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ciao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ciao.to_param, :ciao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ciao as @ciao" do
        ciao = Ciao.create! valid_attributes
        put :update, {:id => ciao.to_param, :ciao => valid_attributes}, valid_session
        assigns(:ciao).should eq(ciao)
      end

      it "redirects to the ciao" do
        ciao = Ciao.create! valid_attributes
        put :update, {:id => ciao.to_param, :ciao => valid_attributes}, valid_session
        response.should redirect_to(ciao)
      end
    end

    describe "with invalid params" do
      it "assigns the ciao as @ciao" do
        ciao = Ciao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ciao.any_instance.stub(:save).and_return(false)
        put :update, {:id => ciao.to_param, :ciao => {}}, valid_session
        assigns(:ciao).should eq(ciao)
      end

      it "re-renders the 'edit' template" do
        ciao = Ciao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ciao.any_instance.stub(:save).and_return(false)
        put :update, {:id => ciao.to_param, :ciao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ciao" do
      ciao = Ciao.create! valid_attributes
      expect {
        delete :destroy, {:id => ciao.to_param}, valid_session
      }.to change(Ciao, :count).by(-1)
    end

    it "redirects to the ciaos list" do
      ciao = Ciao.create! valid_attributes
      delete :destroy, {:id => ciao.to_param}, valid_session
      response.should redirect_to(ciaos_url)
    end
  end

end
