require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DestinosController do

  # This should return the minimal set of attributes required to create a valid
  # Destino. As you add validations to Destino, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DestinosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all destinos as @destinos" do
      destino = Destino.create! valid_attributes
      get :index, {}, valid_session
      assigns(:destinos).should eq([destino])
    end
  end

  describe "GET show" do
    it "assigns the requested destino as @destino" do
      destino = Destino.create! valid_attributes
      get :show, {:id => destino.to_param}, valid_session
      assigns(:destino).should eq(destino)
    end
  end

  describe "GET new" do
    it "assigns a new destino as @destino" do
      get :new, {}, valid_session
      assigns(:destino).should be_a_new(Destino)
    end
  end

  describe "GET edit" do
    it "assigns the requested destino as @destino" do
      destino = Destino.create! valid_attributes
      get :edit, {:id => destino.to_param}, valid_session
      assigns(:destino).should eq(destino)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Destino" do
        expect {
          post :create, {:destino => valid_attributes}, valid_session
        }.to change(Destino, :count).by(1)
      end

      it "assigns a newly created destino as @destino" do
        post :create, {:destino => valid_attributes}, valid_session
        assigns(:destino).should be_a(Destino)
        assigns(:destino).should be_persisted
      end

      it "redirects to the created destino" do
        post :create, {:destino => valid_attributes}, valid_session
        response.should redirect_to(Destino.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved destino as @destino" do
        # Trigger the behavior that occurs when invalid params are submitted
        Destino.any_instance.stub(:save).and_return(false)
        post :create, {:destino => {}}, valid_session
        assigns(:destino).should be_a_new(Destino)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Destino.any_instance.stub(:save).and_return(false)
        post :create, {:destino => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested destino" do
        destino = Destino.create! valid_attributes
        # Assuming there are no other destinos in the database, this
        # specifies that the Destino created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Destino.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => destino.to_param, :destino => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested destino as @destino" do
        destino = Destino.create! valid_attributes
        put :update, {:id => destino.to_param, :destino => valid_attributes}, valid_session
        assigns(:destino).should eq(destino)
      end

      it "redirects to the destino" do
        destino = Destino.create! valid_attributes
        put :update, {:id => destino.to_param, :destino => valid_attributes}, valid_session
        response.should redirect_to(destino)
      end
    end

    describe "with invalid params" do
      it "assigns the destino as @destino" do
        destino = Destino.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Destino.any_instance.stub(:save).and_return(false)
        put :update, {:id => destino.to_param, :destino => {}}, valid_session
        assigns(:destino).should eq(destino)
      end

      it "re-renders the 'edit' template" do
        destino = Destino.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Destino.any_instance.stub(:save).and_return(false)
        put :update, {:id => destino.to_param, :destino => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested destino" do
      destino = Destino.create! valid_attributes
      expect {
        delete :destroy, {:id => destino.to_param}, valid_session
      }.to change(Destino, :count).by(-1)
    end

    it "redirects to the destinos list" do
      destino = Destino.create! valid_attributes
      delete :destroy, {:id => destino.to_param}, valid_session
      response.should redirect_to(destinos_url)
    end
  end

end
