require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaisesController do

  # This should return the minimal set of attributes required to create a valid
  # Paise. As you add validations to Paise, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaisesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all paises as @paises" do
      paise = Paise.create! valid_attributes
      get :index, {}, valid_session
      assigns(:paises).should eq([paise])
    end
  end

  describe "GET show" do
    it "assigns the requested paise as @paise" do
      paise = Paise.create! valid_attributes
      get :show, {:id => paise.to_param}, valid_session
      assigns(:paise).should eq(paise)
    end
  end

  describe "GET new" do
    it "assigns a new paise as @paise" do
      get :new, {}, valid_session
      assigns(:paise).should be_a_new(Paise)
    end
  end

  describe "GET edit" do
    it "assigns the requested paise as @paise" do
      paise = Paise.create! valid_attributes
      get :edit, {:id => paise.to_param}, valid_session
      assigns(:paise).should eq(paise)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Paise" do
        expect {
          post :create, {:paise => valid_attributes}, valid_session
        }.to change(Paise, :count).by(1)
      end

      it "assigns a newly created paise as @paise" do
        post :create, {:paise => valid_attributes}, valid_session
        assigns(:paise).should be_a(Paise)
        assigns(:paise).should be_persisted
      end

      it "redirects to the created paise" do
        post :create, {:paise => valid_attributes}, valid_session
        response.should redirect_to(Paise.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved paise as @paise" do
        # Trigger the behavior that occurs when invalid params are submitted
        Paise.any_instance.stub(:save).and_return(false)
        post :create, {:paise => {}}, valid_session
        assigns(:paise).should be_a_new(Paise)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Paise.any_instance.stub(:save).and_return(false)
        post :create, {:paise => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested paise" do
        paise = Paise.create! valid_attributes
        # Assuming there are no other paises in the database, this
        # specifies that the Paise created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Paise.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => paise.to_param, :paise => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested paise as @paise" do
        paise = Paise.create! valid_attributes
        put :update, {:id => paise.to_param, :paise => valid_attributes}, valid_session
        assigns(:paise).should eq(paise)
      end

      it "redirects to the paise" do
        paise = Paise.create! valid_attributes
        put :update, {:id => paise.to_param, :paise => valid_attributes}, valid_session
        response.should redirect_to(paise)
      end
    end

    describe "with invalid params" do
      it "assigns the paise as @paise" do
        paise = Paise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Paise.any_instance.stub(:save).and_return(false)
        put :update, {:id => paise.to_param, :paise => {}}, valid_session
        assigns(:paise).should eq(paise)
      end

      it "re-renders the 'edit' template" do
        paise = Paise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Paise.any_instance.stub(:save).and_return(false)
        put :update, {:id => paise.to_param, :paise => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested paise" do
      paise = Paise.create! valid_attributes
      expect {
        delete :destroy, {:id => paise.to_param}, valid_session
      }.to change(Paise, :count).by(-1)
    end

    it "redirects to the paises list" do
      paise = Paise.create! valid_attributes
      delete :destroy, {:id => paise.to_param}, valid_session
      response.should redirect_to(paises_url)
    end
  end

end
