require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PassageirosController do

  # This should return the minimal set of attributes required to create a valid
  # Passageiro. As you add validations to Passageiro, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PassageirosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all passageiros as @passageiros" do
      passageiro = Passageiro.create! valid_attributes
      get :index, {}, valid_session
      assigns(:passageiros).should eq([passageiro])
    end
  end

  describe "GET show" do
    it "assigns the requested passageiro as @passageiro" do
      passageiro = Passageiro.create! valid_attributes
      get :show, {:id => passageiro.to_param}, valid_session
      assigns(:passageiro).should eq(passageiro)
    end
  end

  describe "GET new" do
    it "assigns a new passageiro as @passageiro" do
      get :new, {}, valid_session
      assigns(:passageiro).should be_a_new(Passageiro)
    end
  end

  describe "GET edit" do
    it "assigns the requested passageiro as @passageiro" do
      passageiro = Passageiro.create! valid_attributes
      get :edit, {:id => passageiro.to_param}, valid_session
      assigns(:passageiro).should eq(passageiro)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Passageiro" do
        expect {
          post :create, {:passageiro => valid_attributes}, valid_session
        }.to change(Passageiro, :count).by(1)
      end

      it "assigns a newly created passageiro as @passageiro" do
        post :create, {:passageiro => valid_attributes}, valid_session
        assigns(:passageiro).should be_a(Passageiro)
        assigns(:passageiro).should be_persisted
      end

      it "redirects to the created passageiro" do
        post :create, {:passageiro => valid_attributes}, valid_session
        response.should redirect_to(Passageiro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved passageiro as @passageiro" do
        # Trigger the behavior that occurs when invalid params are submitted
        Passageiro.any_instance.stub(:save).and_return(false)
        post :create, {:passageiro => {}}, valid_session
        assigns(:passageiro).should be_a_new(Passageiro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Passageiro.any_instance.stub(:save).and_return(false)
        post :create, {:passageiro => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested passageiro" do
        passageiro = Passageiro.create! valid_attributes
        # Assuming there are no other passageiros in the database, this
        # specifies that the Passageiro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Passageiro.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => passageiro.to_param, :passageiro => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested passageiro as @passageiro" do
        passageiro = Passageiro.create! valid_attributes
        put :update, {:id => passageiro.to_param, :passageiro => valid_attributes}, valid_session
        assigns(:passageiro).should eq(passageiro)
      end

      it "redirects to the passageiro" do
        passageiro = Passageiro.create! valid_attributes
        put :update, {:id => passageiro.to_param, :passageiro => valid_attributes}, valid_session
        response.should redirect_to(passageiro)
      end
    end

    describe "with invalid params" do
      it "assigns the passageiro as @passageiro" do
        passageiro = Passageiro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Passageiro.any_instance.stub(:save).and_return(false)
        put :update, {:id => passageiro.to_param, :passageiro => {}}, valid_session
        assigns(:passageiro).should eq(passageiro)
      end

      it "re-renders the 'edit' template" do
        passageiro = Passageiro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Passageiro.any_instance.stub(:save).and_return(false)
        put :update, {:id => passageiro.to_param, :passageiro => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested passageiro" do
      passageiro = Passageiro.create! valid_attributes
      expect {
        delete :destroy, {:id => passageiro.to_param}, valid_session
      }.to change(Passageiro, :count).by(-1)
    end

    it "redirects to the passageiros list" do
      passageiro = Passageiro.create! valid_attributes
      delete :destroy, {:id => passageiro.to_param}, valid_session
      response.should redirect_to(passageiros_url)
    end
  end

end
