require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PassageirovoosController do

  # This should return the minimal set of attributes required to create a valid
  # Passageirovoo. As you add validations to Passageirovoo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PassageirovoosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all passageirovoos as @passageirovoos" do
      passageirovoo = Passageirovoo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:passageirovoos).should eq([passageirovoo])
    end
  end

  describe "GET show" do
    it "assigns the requested passageirovoo as @passageirovoo" do
      passageirovoo = Passageirovoo.create! valid_attributes
      get :show, {:id => passageirovoo.to_param}, valid_session
      assigns(:passageirovoo).should eq(passageirovoo)
    end
  end

  describe "GET new" do
    it "assigns a new passageirovoo as @passageirovoo" do
      get :new, {}, valid_session
      assigns(:passageirovoo).should be_a_new(Passageirovoo)
    end
  end

  describe "GET edit" do
    it "assigns the requested passageirovoo as @passageirovoo" do
      passageirovoo = Passageirovoo.create! valid_attributes
      get :edit, {:id => passageirovoo.to_param}, valid_session
      assigns(:passageirovoo).should eq(passageirovoo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Passageirovoo" do
        expect {
          post :create, {:passageirovoo => valid_attributes}, valid_session
        }.to change(Passageirovoo, :count).by(1)
      end

      it "assigns a newly created passageirovoo as @passageirovoo" do
        post :create, {:passageirovoo => valid_attributes}, valid_session
        assigns(:passageirovoo).should be_a(Passageirovoo)
        assigns(:passageirovoo).should be_persisted
      end

      it "redirects to the created passageirovoo" do
        post :create, {:passageirovoo => valid_attributes}, valid_session
        response.should redirect_to(Passageirovoo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved passageirovoo as @passageirovoo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Passageirovoo.any_instance.stub(:save).and_return(false)
        post :create, {:passageirovoo => {}}, valid_session
        assigns(:passageirovoo).should be_a_new(Passageirovoo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Passageirovoo.any_instance.stub(:save).and_return(false)
        post :create, {:passageirovoo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested passageirovoo" do
        passageirovoo = Passageirovoo.create! valid_attributes
        # Assuming there are no other passageirovoos in the database, this
        # specifies that the Passageirovoo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Passageirovoo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => passageirovoo.to_param, :passageirovoo => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested passageirovoo as @passageirovoo" do
        passageirovoo = Passageirovoo.create! valid_attributes
        put :update, {:id => passageirovoo.to_param, :passageirovoo => valid_attributes}, valid_session
        assigns(:passageirovoo).should eq(passageirovoo)
      end

      it "redirects to the passageirovoo" do
        passageirovoo = Passageirovoo.create! valid_attributes
        put :update, {:id => passageirovoo.to_param, :passageirovoo => valid_attributes}, valid_session
        response.should redirect_to(passageirovoo)
      end
    end

    describe "with invalid params" do
      it "assigns the passageirovoo as @passageirovoo" do
        passageirovoo = Passageirovoo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Passageirovoo.any_instance.stub(:save).and_return(false)
        put :update, {:id => passageirovoo.to_param, :passageirovoo => {}}, valid_session
        assigns(:passageirovoo).should eq(passageirovoo)
      end

      it "re-renders the 'edit' template" do
        passageirovoo = Passageirovoo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Passageirovoo.any_instance.stub(:save).and_return(false)
        put :update, {:id => passageirovoo.to_param, :passageirovoo => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested passageirovoo" do
      passageirovoo = Passageirovoo.create! valid_attributes
      expect {
        delete :destroy, {:id => passageirovoo.to_param}, valid_session
      }.to change(Passageirovoo, :count).by(-1)
    end

    it "redirects to the passageirovoos list" do
      passageirovoo = Passageirovoo.create! valid_attributes
      delete :destroy, {:id => passageirovoo.to_param}, valid_session
      response.should redirect_to(passageirovoos_url)
    end
  end

end
